- name: Create test directory if it does not exist
  file:
    path: /root/test_folder
    state: directory
    mode: '0755'

- name: Get all files and folders in /home/centos
  command: ls /home/centos
  register: data
  delegate_to: localhost

 - name: Create file with content from variable
   copy:
     dest: "/root/test_folder/information.txt"
     content: |
       "{{ data.stdout }}"